### PR TITLE
feat: Add EC2 Auto Scaling VPC endpoint

### PR DESCRIPTION
**Pull request by pserrano**
Add the new Ec2 Auto Scaling vpc endpoint - https://docs.aws.amazon.com/autoscaling/ec2/userguide/ec2-auto-scaling-vpc-endpoints.html

### CODE REVIEW

**Comment by abohne** [comment]
@pserrano Could you resolve the conflicts on this branch?

**Comment by pserrano** [comment]
> @pserrano Could you resolve the conflicts on this branch?

Ok, let me check.

**Comment by pserrano** [comment]
@abohne Resolved I guess. Could you take a final check? Thanks

**Comment by abohne** [comment]
@antonbabenko Could you review and merge?

**Comment by antonbabenko** [comment]
Thanks @pserrano!

[v2.33.0](https://github.com/terraform-aws-modules/terraform-aws-vpc/releases/v2.33.0) has been just released.

**Pull request merged**
