### PR TITLE
fix: Manage route tables for multiple database subnets

### PR DESCRIPTION
**Pull request by y-batsianouski**
## Description
Module fails when I try to create multiple database subnets with `create_database_subnet_route_table = true` and `single_nat_gateway = false`

## Motivation and Context
When I try to create multiple database subnets with it's own route tables, module tries to create:
1. multiple db subnets
2. One route table for multiple database subnets
2. Multiple routes for each NAT gateway. Points all this routes to one route table and fails.

## Breaking Changes
There was no possibility to create multiple db subnets with `create_database_subnet_route_table = true` and `single_nat_gateway = false`. So there are shouldn't be breaking changes.

### Case 1
```terraform
module "vpc-test" {
  ...
  cidr             = "10.40.0.0/16"
  azs              = ["us-east-1a", "us-east-1b"]
  public_subnets   = ["10.40.1.0/24", "10.40.2.0/24"]
  private_subnets  = ["10.40.3.0/24", "10.40.4.0/24"]
  database_subnets = ["10.40.5.0/24", "10.40.6.0/24"]

  single_nat_gateway                     = false
  create_database_subnet_route_table     = true
  create_database_nat_gateway_route      = true
  ...
}
```
Creates 2 route tables for database subnets. Points each route table to appropriate NAT gateway

### Case 2
```terraform
module "vpc-test" {
  ...
  cidr             = "10.40.0.0/16"
  azs              = ["us-east-1a", "us-east-1b"]
  public_subnets   = ["10.40.1.0/24", "10.40.2.0/24"]
  private_subnets  = ["10.40.3.0/24", "10.40.4.0/24"]
  database_subnets = ["10.40.5.0/24", "10.40.6.0/24"]

  single_nat_gateway                     = true
  create_database_subnet_route_table     = true
  create_database_nat_gateway_route      = true
  ...
}
```
Creates 1 route table for all database subnets. Points route table to single NAT gateway

### Case 3
```terraform
module "vpc-test" {
  ...
  cidr             = "10.40.0.0/16"
  azs              = ["us-east-1a", "us-east-1b"]
  public_subnets   = ["10.40.1.0/24", "10.40.2.0/24"]
  private_subnets  = ["10.40.3.0/24", "10.40.4.0/24"]
  database_subnets = ["10.40.5.0/24", "10.40.6.0/24"]
  
  create_database_subnet_route_table     = true
  create_database_nat_gateway_route      = false
  create_database_internet_gateway_route = true
  ...
}
```
Creates 1 route table for all database subnets. Points route table to internet gateway

### CODE REVIEW

**Comment by DrFaust92** [comment]
Looks good to me, ill try to test all the cases.

**Comment by y-batsianouski** [comment]
@antonbabenko @DrFaust92 Did you have a chance to look at this? Thanks!

**Comment by Chili-Man** [comment]
@y-batsianouski @antonbabenko @DrFaust92  I can confirm that this fixes the issue I reported https://github.com/terraform-aws-modules/terraform-aws-vpc/issues/516

**Comment by y-batsianouski** [comment]
> @y-batsianouski Can you please update this with the base branch?
> 
> @antonbabenko @DrFaust92 I can confirm that this fixes the issue I reported #516

@Chili-Man I'll try to manage this soon. But It's not very interesting for me now because I've written my own tf module for VPC which was inspired by this module but provides much more flexibility: https://registry.terraform.io/modules/y-batsianouski/vpc/aws. 
Unfortunately full documentation isn't completed yet, but I'm going to update it soon.

**Comment by Chili-Man** [comment]
@y-batsianouski I understand, thanks for the update;  I can carry this forward then; I'll open a new pr with these changes

**Comment by Chili-Man** [comment]
@y-batsianouski  I've opened this pr to carry the changes forward here: https://github.com/terraform-aws-modules/terraform-aws-vpc/pull/518 . Feel free to close this PR

**Comment by y-batsianouski** [comment]
Closining. @Chili-Man handover this changes in it's PR: https://github.com/terraform-aws-modules/terraform-aws-vpc/pull/518

**Comment by bryantbiggs** [comment]
hi all, this is fixed now in #518

**Pull request closed without merging**
