### PR TITLE
fix: Correctly manage route tables for database subnets when multiple NAT gateways present

### PR DESCRIPTION
**Pull request by Chili-Man**
## Description
Original pull request from @y-batsianouski  (https://github.com/terraform-aws-modules/terraform-aws-vpc/pull/494). 
I'm taking it forward because the aforementioned author no longer has interest in carrying the PR forward. 

The module fails when trying to add the NAT gateway route to the database route table when there is more then a single NAT gateway. Fixes https://github.com/terraform-aws-modules/terraform-aws-vpc/issues/516

## Motivation and Context
In particular, I want to enable the NAT gateway route for the database route tables. When I tried that by setting the following options, 

```hcl
  database_subnets  = [
    "10.50.160.0/22",
    "10.50.164.0/22",
    "10.50.168.0/22",
    "10.50.172.0/22",
    "10.50.176.0/22",
   ]

  enable_nat_gateway       = true
  one_nat_gateway_per_az   = true
  single_nat_gateway       = false

  create_database_subnet_route_table = true
  create_database_nat_gateway_route  = true 
  create_database_subnet_group       = false
 ```

it fails with:

```console
Error: Error creating route: RouteAlreadyExists: The route identified by 0.0.0.0/0 already exists.
	status code: 400, request id: 6739c57a-097a-433d-a032-28fe6835033f

Error: Error creating route: RouteAlreadyExists: The route identified by 0.0.0.0/0 already exists.
	status code: 400, request id: c4ab4221-dcc8-4eb0-b976-e5f15f6c7f47

Error: Error creating route: RouteAlreadyExists: The route identified by 0.0.0.0/0 already exists.
	status code: 400, request id: 99a91d24-cb7b-4b4c-90db-e68e8faf1625

Error: Error creating route: RouteAlreadyExists: The route identified by 0.0.0.0/0 already exists.
	status code: 400, request id: ad82436e-223e-4f90-91e9-5b12fc096c11
```

The problem lies here:

The database route table: https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/master/main.tf#L231-L232
The database route rule for adding the nat gateway: https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/master/main.tf#L257-L260
Only one database route table for all of the database subnets is created, but when enabling the create_database_nat_gateway_route and one_nat_gateway_per_az option, the database route rule resource expects there to be more then 1 database route table. However, what ends up happening is that it tries to modify that single database route table the same number of times there are nat gateways which causes the above RouteAlreadyExists error.

The solution would be to create multiple database route tables when both create_database_nat_gateway_route and one_nat_gateway_per_az are enabled, then it should work as expected.

## Breaking Changes
There are no breaking changes as this particular behavior was not working beforehand. The changes here preserve the existing behavior if there is only a single nat gateway. 

## How Has This Been Tested?
The following cases have been tested: 

### Case 1
```hcl
module "vpc-test" {
  ...
  cidr             = "10.40.0.0/16"
  azs              = ["us-east-1a", "us-east-1b"]
  public_subnets   = ["10.40.1.0/24", "10.40.2.0/24"]
  private_subnets  = ["10.40.3.0/24", "10.40.4.0/24"]
  database_subnets = ["10.40.5.0/24", "10.40.6.0/24"]

  single_nat_gateway                     = false
  create_database_subnet_route_table     = true
  create_database_nat_gateway_route      = true
  ...
}
```
Creates 2 route tables for database subnets. Points each route table to appropriate NAT gateway

###Case 2
```hcl
module "vpc-test" {
  ...
  cidr             = "10.40.0.0/16"
  azs              = ["us-east-1a", "us-east-1b"]
  public_subnets   = ["10.40.1.0/24", "10.40.2.0/24"]
  private_subnets  = ["10.40.3.0/24", "10.40.4.0/24"]
  database_subnets = ["10.40.5.0/24", "10.40.6.0/24"]

  single_nat_gateway                     = true
  create_database_subnet_route_table     = true
  create_database_nat_gateway_route      = true
  ...
}
```

Creates 1 route table for all database subnets. Points route table to single NAT gateway

### Case 3

```hcl
module "vpc-test" {
  ...
  cidr             = "10.40.0.0/16"
  azs              = ["us-east-1a", "us-east-1b"]
  public_subnets   = ["10.40.1.0/24", "10.40.2.0/24"]
  private_subnets  = ["10.40.3.0/24", "10.40.4.0/24"]
  database_subnets = ["10.40.5.0/24", "10.40.6.0/24"]
  
  create_database_subnet_route_table     = true
  create_database_nat_gateway_route      = false
  create_database_internet_gateway_route = true
  ...
}
```
Creates 1 route table for all database subnets. Points route table to internet gateway

### Case 4
```
module "vpc-test" {
  cidr             = "10.50.0.0/16"
  azs              = ["us-east-1a", "us-east-1b", "us-east-1c", "us-east-1d", "us-east-1f"]

  public_subnets   = [
  "10.50.200.0/24",
  "10.50.201.0/24",
  "10.50.202.0/24",
  "10.50.203.0/24",
  "10.50.204.0/24",
]
  private_subnets  = [
    "10.50.0.0/19",
    "10.50.32.0/19",
    "10.50.64.0/19",
    "10.50.96.0/19",
    "10.50.128.0/19",
  ]


  database_subnets  = [
    "10.50.160.0/22",
    "10.50.164.0/22",
    "10.50.168.0/22",
    "10.50.172.0/22",
    "10.50.176.0/22",
   ]

  enable_nat_gateway       = true
  one_nat_gateway_per_az   = true
  single_nat_gateway       = false

  create_database_subnet_route_table = true
  create_database_nat_gateway_route  = true 
  create_database_subnet_group       = false

```
Creates 5 route tables, one per az for the database subnets; each of the route tables has a corresponding route rule to one of the NAT gateways. This is similar to case 1.

### CODE REVIEW

**Comment by y-batsianouski** [comment]
Thanks @Chili-Man to handover this changes!

**Review by y-batsianouski — APPROVED** [review]

**Comment by Chili-Man** [comment]
@antonbabenko @DrFaust92 any chance you guys can take a look at reviewing / merging this in?

**Comment by Chili-Man** [comment]
@antonbabenko @DrFaust92  anything I can do to help get this pr reviewed/merged in ?

**Comment by antonbabenko** [comment]
Hi @Chili-Man !

Thanks for this update. I can't promise when I have time to review such non-trivial PR, but maybe other people can review it and comment on it faster.

**Comment by Chili-Man** [comment]
no worries @antonbabenko , I've tried pinging @DrFaust92 as well but to no avail. Is there anyone else I can ping ?

**Comment by antonbabenko** [comment]
Maybe somebody from @terraform-aws-modules/triage-supporters can review and verify various cases.

**Comment by Chili-Man** [comment]
@antonbabenko   @terraform-aws-modules/triage-supporters  it's been a month now since this pr was open; can I do anything from my side to show you guys that the various cases have been properly verified?

**Comment by DrFaust92** [comment]
Hey @Chili-Man, ill try to take a close look at this the coming week.

**Comment by Chili-Man** [comment]
thanks @DrFaust92 ; let me know if there's anything you need to get this through

**Comment by hche608** [comment]
would we get this merge into master?

**Comment by Chili-Man** [comment]
@DrFaust92 @antonbabenko  any updates on this?

**Comment by Chili-Man** [comment]
Happy new years @DrFaust92 @antonbabenko ; any chance we can get an update on this?

**Comment by Chili-Man** [comment]
@antonbabenko @DrFaust92  hey what I can do to help push this through

**Comment by DrFaust92** [comment]
Tested by running simple vpc example with database_subnets on main branch and than upgrading by switching to this branch.

upgrade worked fine and created multiple subnets as expected. and reducing to a single one again when single nat is enabled.

@antonbabenko LGTM 🚀

**Comment by Chili-Man** [comment]
thanks @DrFaust92 , appreciate the review!

**Review by DrFaust92 — APPROVED** [review]

**Comment by antonbabenko** [comment]
What a day!

Thanks @Chili-Man for being so patient for 4 months!

[v2.72.0](https://github.com/terraform-aws-modules/terraform-aws-vpc/releases/v2.72.0) has been just released.

**Comment by Chili-Man** [comment]
@antonbabenko thank you for getting it merged in 💯

**Pull request merged**
