### PR TITLE
feat: Add support for `dns_options` on VPC endpoints

### LINKED ISSUE #982: Cannot create S3 VPC Endpoint with private DNS enabled.
## Description

When trying to create an S3 endpoint with `private_dns_enabled = true`, an error is returned when using the vpc-endpoints module.  I've verified the issue with aws provider version 5.16.2 and this vpc module v5.1.2.

The error message is 
```
│ Error: creating EC2 VPC Endpoint (com.amazonaws.us-west-2.s3): InvalidParameter: To set PrivateDnsOnlyForInboundResolverEndpoint to true, the VPC vpc-xxxxxxx must have a Gateway endpoint for the service.
│       status code: 400, request id: cc137867-946f-4e06-ada7-7f5a153440d4
│ 
│   with module.application_vpc.module.vpc_endpoints.aws_vpc_endpoint.this["s3"],
│   on .terraform/modules/application_vpc.vpc_endpoints/modules/vpc-endpoints/main.tf line 23, in resource "aws_vpc_endpoint" "this":
│   23: resource "aws_vpc_endpoint" "this" {
```

This is  referencing aws provider bug mentioned in https://github.com/hashicorp/terraform-provider-aws/issues/32407 and https://github.com/hashicorp/terraform-provider-aws/issues/31117

Per the docs https://aws.amazon.com/blogs/storage/introducing-private-dns-support-for-amazon-s3-with-aws-privatelink/ it seems that Scenario 2 (all traffic routed via private endpoint) is not possible.  The default configuration expects to have both a gateway endpoint to S3 (for VPC traffic) and an Interface endpoint (to route on-prem traffic).

We cannot enable a single interface endpoint because the `dns_options. private_dns_only_for_inbound_resolver_endpoint` seems to be getting set to true if `private_dns_enabled` is set to true and the vpc-endpoints module has no provision to override this.

The workaround is to create _both_ a gateway and an interface endpoint to satisfy requirements of scenario 3 in the docs or to create a standalone `aws_vpc_endpoint` resource and not use the vpc-endpoints module for this at all.  We have a need to have all traffic to S3 be private so the first workaround of creating both types of endpoints is not an option.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 5.1.2

- Terraform version:
1.4.6
- Provider version(s):
+ provider registry.terraform.io/hashicorp/aws v5.16.2

## Reproduction Code [Required]

Example:

```
module "vpc_endpoints" {
  source  = "terraform-aws-modules/vpc/aws//modules/vpc-endpoints"
  version = "v5.1.2"

  vpc_id             = module.vpc.vpc_id
  security_group_ids = [module.vpc_endpoints_sg.security_group_id]

  endpoints = {
    s3 = {
      service             = "s3"
      tags                = { Name = "s3-vpc-endpoint" }
      service_type        = "Interface"
      private_dns_enabled = true
    }
  }

  tags = var.default_tags

}
```

see above.

## Expected behavior

Only specify an interface endpoint for S3 with `private_dns_enabled: true` and `private_dns_only_for_inbound_resolver_endpoint: false` to allow for all traffic to S3 be private.

## Actual behavior

Both referenced parameters are set to true and there is not option to explicitly set `private_dns_only_for_inbound_resolver_endpoint` to false within the module.

### Terminal Output Screenshot(s)

n/a

## Additional context

The module should allow for setting options within the `dns_options` block as noted in the resource documentation: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_endpoint#dns_options

### PR DESCRIPTION
**Pull request by erezo9**
## Description

add dns_options block to use it in cases of endpoints that support gateway and interface 

## Motivation and Context
- Resolves #982

## How Has This Been Tested?
- [x] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [X] I have tested and validated these changes using one or more of the provided `examples/*` projects

there is no user input change, if the array is not existend or private_dns_enabled is false it will not trigger a change

tested locally
- [x] I have executed `pre-commit run -a` on my pull request

### CODE REVIEW

**Comment by erezo9** [comment]
@antonbabenko if you could please review this or tag relavent people to review
will be super helpful if this be in the next version

**Review by zach-nicoll-wcq — COMMENTED** [review]
Would love to see this merged!! Currently blocking a private MWAA deployment because Terraform doesn't support this.

**Comment by erezo9** [comment]
@bryantbiggs 
Can you please review this MR, i cant assign reviewers to view this code and it will really help in the provisioning

**Review by bryantbiggs — APPROVED** [review]

**Comment by antonbabenko** [comment]
This PR is included in version 5.5.0 :tada:

**Comment by erezo9** [comment]
@bryantbiggs thanks for merging
why did you change the looping validation and the check on the private_dns_enabled?
i added it so it could prevent users from using this when its type gateway and when private_dns_enabled = true the value should not exist

**Comment by bryantbiggs** [comment]
> the value should not exist

Then users should not provide it. Sometimes we can provide the means to help users avoid misconfiguration, but in this scenario the logic would be overly complex

**Pull request merged**
