### PR TITLE
Add Output Of Subnet ARNs

### PR DESCRIPTION
**Pull request by blaines**
Facilitates resource access manager, subnet sharing across accounts

### CODE REVIEW

**Comment by antonbabenko** [comment]
@blaines Looks good to me. Do you think it makes sense to output ARNs of all resources? (I have not worked with RAM myself, so not sure how it works in details).

**Comment by blaines** [comment]
Maybe, right now it looks like RAM is for Subnets, Transit Gateways, and Resolver Rules. So I think there's nothing else to add at this time. (This doesn't to Transit right?)

**Comment by antonbabenko** [comment]
@blaines Thanks for this PR. I think you are right, you have added ARNs to all resources managed by this module.

[v1.64.0](https://github.com/terraform-aws-modules/terraform-aws-vpc/releases/v1.64.0) has been released.

**Comment by dyna-dot** [comment]
[CHANGELOG.zip](https://github.com/terraform-aws-modules/terraform-aws-vpc/files/3136379/CHANGELOG.zip)

**Pull request merged**
