### PR TITLE
Missing VPC Endpoints

### PR DESCRIPTION
**Pull request by DrFaust92**
Adds VPC Endpoints for :

- [x] CloudWatch (Monitoring, Logs, Events)
- [x] SNS
- [x] CloudTrail
- [x] ELB

### CODE REVIEW

**Comment by DrFaust92** [comment]
Resolves #262

**Comment by nunofernandes** [comment]
Will this patch also support (or will be backported to) version 1.XX of the module?

**Comment by DrFaust92** [comment]
@antonbabenko fixed formatting using hook.

@nunofernandes i can branch the latest 1.XX tag and make changes there but not sure if owner of repo wants to support this or has a release process for new 1.XX versions.

**Comment by antonbabenko** [comment]
[v2.1.0](https://github.com/terraform-aws-modules/terraform-aws-vpc/releases/v2.1.0) has been released and it requires Terraform 0.12.

I am not sure how long we will support Terraform 0.11 and what kind of new features should be going there, but I think it is a good idea to backport this PR. Please submit a PR to [terraform011 branch](https://github.com/terraform-aws-modules/terraform-aws-vpc/tree/terraform011).

**Pull request merged**
