### PR TITLE
Fixed aws_vpn_gateway_route_propagation for default route table

### LINKED ISSUE #85: private_propagating_vgws
I'm having trouble using the following with this module:

```
resource "aws_vpn_gateway_route_propagation" "SpokeA" {
  count          = "${length(module.spokeA.private_route_table_ids)}"
  vpn_gateway_id = "${module.spokeA.vgw_id}"
  route_table_id = "${element(module.spokeA.private_route_table_ids, count.index)}"
}
```

The problem I'm having is every other time I run Terraform the propagation is turned off and then on again.

I noticed private_propagating_vgws in the variables and main.tf of this module but am a bit puzzled as to how to use this parameter in combination with enable_vpn_gateway="true".

Can someone provide an example of the correct way to enable route propagation on the route tables associated with the VPC created by this module?

### PR DESCRIPTION
**Pull request by antonbabenko**
Fix #85

### CODE REVIEW

**Comment by sc250024** [comment]
@antonbabenko Was there a reason this hadn't been merged yet? I agree with @tyrken , it would be nice to have this feature in the VPC module. Let me know if you need help with testing or something else. Thank you!

**Comment by antonbabenko** [comment]
Yes, we should merge this and it is primarily correct, but should be rebased because `aws_main_route_table_association` and `aws_default_route_table` were removed since this PR was created.

Please finish this and test it properly.

**Comment by sc250024** [comment]
@antonbabenko Without write access I cannot change the branch directly. Do you want me to spin up a new PR based off a fork?

**Comment by antonbabenko** [comment]
Yes, please check out this PR and make a new fork. I can't grant write access to this repo.

**Comment by sc250024** [comment]
This PR can be closed. Re-opened here: https://github.com/terraform-aws-modules/terraform-aws-vpc/pull/133

**Comment by DrFaust92** [comment]
@antonbabenko can we close this?

**Pull request closed without merging**
