### PR TITLE
feat: Added device_name to customer gateway object.

### PR DESCRIPTION
**Pull request by byjg**
## Description
Minimal change adding the `device_name` property into the `aws_customer_gateway` resource.

## Motivation and Context
I already had a Customer Gateway created, and when I imported the resource state into this module, terraform was trying to recreate the resource. Without this change, I  cannot use the module with pre-existent AWS customer gateway resources with the "device_name" set. 

## Breaking Changes
There are no break changes. 

## How Has This Been Tested?
I have two Gateway resources. One with the `device_name` property set, and the other don't set. 

```
    customer_gateways = {
      "cgw1"      = {
        bgp_asn     = 65000
        ip_address  = "1.2.3.4"
        device_name = "USG"
      },
      "cgw2" = {
        bgp_asn    = 65000
        ip_address = "5.6.7.8"
      },
    }
```

I tested both importing the resources and created the resources from scratch.

### CODE REVIEW

**Comment by bryantbiggs** [comment]
thanks for the PR @byjg - this looks good! could you update the example similar to what you have shown above please https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/2ee908db287a834e263559ec4b35ebac625a7dba/examples/complete-vpc/main.tf#L47-L56

**Comment by byjg** [comment]
@bryantbiggs example added. Thanks

**Review by antonbabenko — CHANGES_REQUESTED** [review]
Please update `versions.tf` file here and in example (probably) since `device_name` was introduced in v3.28.0 of Terraform AWS provider.

**Comment by byjg** [comment]
@antonbabenko version updated.

**Comment by antonbabenko** [comment]
Thanks, @byjg !

[v3.6.0](https://github.com/terraform-aws-modules/terraform-aws-vpc/releases/v3.6.0) has been just released.

**Pull request merged**
