### PR TITLE
Added basic support for an Ubuntu 18.04 NAT instance gateway

### PR DESCRIPTION
**Pull request by bonovoxly**
# Description

This PR attempts to address #250 .

It adds support for a NAT instance gateway, using Ubuntu 18.04 as the AMI. Note that it requires an AWS keypair to be created and named first. 

Hopefully the conditionals are sound, I did test back and forth going from an AWS managed NAT gateway to an instance, and it seemed to work well.

### CODE REVIEW

**Comment by bonovoxly** [comment]
I'm going to close this; it opens a pandoras box of things to deal with that might not be worth it.

**Comment by antonbabenko** [comment]
Bill, if you have time and interest, I think it would be a better idea to improve [this NAT instance module](https://github.com/terraform-community-modules/tf_aws_nat) which we already have, add support for integration with it and document in details with examples how this can be done.

**Comment by bonovoxly** [comment]
Roger that, @antonbabenko . It's a bummer, I found a fairly clean solution, but I worry that the amount of options that someone may want.

Regardless, I can reopen the PR if there's enough demand for a simple ubuntu nat gateway.

**Comment by antonbabenko** [comment]
I agree, there are lots of details and options always.

No need to open if you are not going to work on it. _I am chasing and closing/resolving issues. Fewer issues = less work for me._ :)

**Pull request closed without merging**
