### PR TITLE
feat: Add routes table association and route attachment outputs

### PR DESCRIPTION
**Pull request by quentin9696**
This PR just add the route table association and route attachment outputs. 

This can be required for some inter-provider dependency (like eks, who need a valid internet connection to run)

### CODE REVIEW

**Comment by quentin9696** [comment]
Ready for review

**Comment by digitalassembly** [comment]
hey guys, any progress on releasing this? Its really holding us up =/

**Comment by quentin9696** [comment]
This is still ready for review !

**Comment by quentin9696** [comment]
@digitalassembly 
I created a fork for my company, while this PR is not merged. You can find it here : https://scm.dazzlingwrench.fxinnovation.com/fxinnovation-public/terraform-module-aws-vpc

**Comment by antonbabenko** [comment]
Thanks @quentin9696 !

[v2.34.0](https://github.com/terraform-aws-modules/terraform-aws-vpc/releases/v2.34.0) has been just released with this code.

**Comment by quentin9696** [comment]
Thank you @antonbabenko

**Pull request merged**
