### PR TITLE
v2.69.1 proposal, ensure AWS terraform provider v2.70.0 compatibility

### PR DESCRIPTION
**Pull request by circa10a**
## Description

- Remove s3/dynamodb service endpoint data sources due to incompatible `service_type` parameter.
- Replace dynamic service name from data sources with template strings

## Motivation and Context

After this week's release of privatelink for s3, the fixes implemented in v2.69.0 and v2.70.0 don't mitigate errors when using the AWS Terraform provider `v2.X.X`

Addresses:

- #582
- #585 

## Breaking Changes

This is a proposed patch release for `v2.69.` which did not resolve the original issue.

## How Has This Been Tested?

This was tested by creating vpc endpoint services with AWS Terraform Provider `2.70.0` and that no error occurred.

/cc @tbugfinder

### CODE REVIEW

**Comment by circa10a** [comment]
Any thoughts on this? If none, I'll go ahead and close it.

**Comment by antonbabenko** [comment]
Hi @circa10a ! This looks pretty good, I will take a deeper look at this in a few days and verify how it works.

There is no need to close this one.

**Comment by bryantbiggs** [comment]
hi @circa10a - thanks for the PR! this is a great idea and I have taken this further in https://github.com/terraform-aws-modules/terraform-aws-vpc/pull/597. a couple things to note:
- DynamoDB interface endpoints are currently not supported yet so I have not included that change as you have
- If users were to try to use the S3 interface type, it would fail. I have addressed this as well
- I've updated an example project as well - this is what we use to validate as well as demonstrate changes

**Comment by circa10a** [comment]
Closing in favor of #597

**Pull request closed without merging**
