### PR TITLE
Extend endpoints for AWS Systems Manager use

### PR DESCRIPTION
**Pull request by tbugfinder**
Extend endpoints so that AWS Systems Manager could be setup utilizing endpoints only.

### CODE REVIEW

**Comment by tbugfinder** [comment]
@antonbabenko 
What do you think?
Is it getting to complex or would you merge it?

**Comment by antonbabenko** [comment]
Looks pretty good, please update the code in `examples/complete` to create these endpoints also, and update documentation by running `pre-commit install --install-hooks` to install hooks once, and then `pre-commit run -a`.

**Comment by tbugfinder** [comment]
applied changes to source branch as requested.

**Comment by antonbabenko** [comment]
Make sure that you are using the latest version of [terraform-docs](https://github.com/segmentio/terraform-docs). The rest looks fine.

**Comment by tbugfinder** [comment]
Good catch. Rerun using terraform-docs 0.6.0.

**Comment by tbugfinder** [comment]
@antonbabenko Good to merge?

**Comment by antonbabenko** [comment]
Yes, tomorrow.

I try to work on terraform-aws-modules in bulks during 1-2 days a week.

**Comment by antonbabenko** [comment]
Thanks @tbugfinder !

[v1.54.0](https://github.com/terraform-aws-modules/terraform-aws-vpc/releases/v1.54.0) has been released.

**Pull request merged**
