### PR TITLE
feat: Add database tags per az, feat: Add public and private and database tags per cidr

### PR DESCRIPTION
**Pull request by kahirokunn**
## How Has This Been Tested?
- [x] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [x] I have executed `pre-commit run -a` on my pull request

### CODE REVIEW

**Comment by kahirokunn** [comment]
keep

**Comment by bryantbiggs** [comment]
thank you but this is not something we will be adding to the module at this time

**Comment by kahirokunn** [comment]
@bryantbiggs May I ask why you don't tag them?

**Comment by bryantbiggs** [comment]
because its not a pattern we commonly see used nor do I think its a pattern that we would want to promote (in the world of IPAM and dynamic IP assignment, this will fail horribly)

**Comment by kahirokunn** [comment]
@bryantbiggs https://github.com/terraform-aws-modules/terraform-aws-vpc/pull/901

If so, how about this one?
I feel this style of code is common.

**Comment by kahirokunn** [comment]
I see. Thx.

**Pull request closed without merging**
