### PR TITLE
Adds support to create a subnet to be used by a VPC based elasticsearch domain

### PR DESCRIPTION
**Pull request by jeffsteinmetz**
Adds support to create a subnet to be used by a VPC based elasticsearch domain.
(Does not create the elasticsearch domain, just the subnets)

### CODE REVIEW

**Comment by jeffsteinmetz** [comment]
Example of the result after a `terraform apply` using this PR

Subnets___VPC_Management_Console

**Comment by antonbabenko** [comment]
Jeff, I am going to close this PR because there is no such type of subnet as "elasticsearch" in AWS. It can be any type of subnet (public or private), and this module already allows to create such generic types of subnets.

**Comment by jeffsteinmetz** [comment]
Thank you, I am now wondering with this existing module, can you create multiple private subnets with different naming schemes?
The idea would be to create a private subnet for EC2 docker images, and a "different" private subnet for use with elasticsearch.
The goal was to create another subnet, isolated from any other private subnets.

**Comment by antonbabenko** [comment]
Currently, this module does not have support for different naming schemas but it is possible to use a different length of `azs` and `private_subnets`, for example, look at this example: https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/master/examples/issue-44-asymmetric-private-subnets/main.tf#L15-L18

Also, you can create subnets as `private_subnets` using this module and use a slice of them for different purposes in your code. Eg, values with index 0-2 - private; index 2-4 - elasticsearch.

**Pull request closed without merging**
