### PR TITLE
feat: Add Textract vpc endpoint

### PR DESCRIPTION
**Pull request by pserrano**
Add the new Textract vpc endpoint - https://docs.aws.amazon.com/textract/latest/dg/vpc-interface-endpoints.html

### CODE REVIEW

**Comment by antonbabenko** [comment]
Why did you close this? I was almost clicking the merge button. Doesn't it work?

**Comment by pserrano** [comment]
@antonbabenko sorry I closed because I would like to add semantic things to the commit

**Comment by pserrano** [comment]
@antonbabenko I reopened

**Comment by antonbabenko** [comment]
The commits are being squashed, so there is not much value in each individual commits.

I will review and merge this one now.

**Comment by antonbabenko** [comment]
Thanks, @pserrano !

[v2.55.0](https://github.com/terraform-aws-modules/terraform-aws-vpc/releases/v2.55.0) has been just released.

**Pull request merged**
