### PR TITLE
Enable EKS tagging

### PR DESCRIPTION
**Pull request by nehanikam**

### CODE REVIEW

**Comment by Grejeru** [comment]
Very nice addition, but what if there are multiple clusters on same VPC? It should include possibility to create multiple instances of `kubernetes.io/cluster/<cluster_name>` tags.

**Comment by bryantbiggs** [comment]
thanks @nehanikam for this PR :tada: I don't know if this is something we will be incorporating into the module at this time. I think the best option for something like this is to have a flexible tagging scheme. This PR looks to make changes to a wide range of networking resources and I don't think that complexity is necessary at this time. There are a number of EKS deployments using this module as is so I think we will have to pass on this proposed change

**Comment by DrFaust92** [comment]
FYI, subnet tagging is no longer needed

**Comment by antonbabenko** [comment]
Closing this issue, as discussed above by @bryantbiggs and @DrFaust92

**Pull request closed without merging**
