### PR TITLE
Add tags to VPC Endpoints

### PR DESCRIPTION
**Pull request by DrFaust92**
# Description

* Added new variable for tags that are specific to VPC Endpoints.
* Added tags to each VPC Endpoint that consists of the the general tag map and VPC Endpoint specific tag map

### CODE REVIEW

**Comment by DrFaust92** [comment]
closes #292

**Comment by DrFaust92** [comment]
@antonbabenko, would you like to consider creating a module for VPC Endpoints?

More endpoints and new configuration is being added to endpoints and the VPC module is starting to feel crowded by endpoints

**Comment by antonbabenko** [comment]
@DrFaust92 I am not sure if it makes sense to make a separate VPC endpoints module, yet.

I like that this module has a lot of features and all of the features are related to VPC in one way or another.

**Comment by DrFaust92** [comment]
updated for new vpc endpoints

**Comment by antonbabenko** [comment]
Thanks @DrFaust92 for this addition!

[v2.12.0](https://github.com/terraform-aws-modules/terraform-aws-vpc/releases/v2.12.0) has been just released.

**Pull request merged**
