### PR TITLE
feat: Add public and private tags per az

### PR DESCRIPTION
**Pull request by nitrocode**
## Description
Add public and private tags per az

## Motivation and Context
I want to set up kubernetes controllers that can use a specific subnet by tag. I could use name but our names have a lot of information in them. I would much rather be able to tag a subnet by AZ with certain tags like the AZ itself or the cluster I'm trying to target for this AZ.

## Breaking Changes

None

## How Has This Been Tested?
- [x] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [x] I have executed `pre-commit run -a` on my pull request

```sh
cd examples/simple-vpc
terraform init
terraform plan
```

```hcl
  # module.vpc.aws_subnet.public[0] will be created
  + resource "aws_subnet" "public" {
      + tags                                           = {
          + "Example"           = "ex-simple-vpc"
          + "GithubOrg"         = "terraform-aws-modules"
          + "GithubRepo"        = "terraform-aws-vpc"
          + "Name"              = "overridden-name-public"
          + "availability-zone" = "eu-west-1a"
        }
      + tags_all                                       = {
          + "Example"           = "ex-simple-vpc"
          + "GithubOrg"         = "terraform-aws-modules"
          + "GithubRepo"        = "terraform-aws-vpc"
          + "Name"              = "overridden-name-public"
          + "availability-zone" = "eu-west-1a"
        }
    }

  # module.vpc.aws_subnet.public[1] will be created
  + resource "aws_subnet" "public" {
      + tags                                           = {
          + "Example"           = "ex-simple-vpc"
          + "GithubOrg"         = "terraform-aws-modules"
          + "GithubRepo"        = "terraform-aws-vpc"
          + "Name"              = "overridden-name-public"
        }
      + tags_all                                       = {
          + "Example"           = "ex-simple-vpc"
          + "GithubOrg"         = "terraform-aws-modules"
          + "GithubRepo"        = "terraform-aws-vpc"
          + "Name"              = "overridden-name-public"
        }
    }
```

### CODE REVIEW

**Comment by nitrocode** [comment]
cc: @bryantbiggs @antonbabenko could you please review this when you folks have a chance?

**Comment by nitrocode** [comment]
cc: @bryantbiggs @antonbabenko friendly ping

**Comment by bryantbiggs** [comment]
My personal opinion is that I don't agree with this approach. I am not sure what the intention is, but controllers can be written to query the IMDS to find out what AZ a pod/node is running within

**Comment by nitrocode** [comment]
The goal is to be able to concentrate traffic against a specific AZ.

We can filter the subnet by tag using the aws-load-balancer-controller (for example) but if we cannot tag per subnet AZ, then we cannot filter by AZ. Being able to tag here by subnet AZ, would allow us to control traffic using these controllers.

**Comment by jessegonzalez-life360** [comment]
>  but controllers can be written to query the IMDS to find out what AZ a pod/node is running within

Yes they could, but a feature to allow defining target subnets based on tags exists already. Also, the effort to include that functionality in a controller would be more complex than what is proposed here.

Without the ability to tag subnets per AZ, one has some options:

- click ops
- using the terraform null_resource with provisioner to tag subnets as needed

With @nitrocode's submission, one can accomplish tagging subnets as needed to satisfy the single AZ target, or any combination of subnet aggregation tagging based on business needs.

**Comment by nitrocode** [comment]
cc: @bryantbiggs (friendly ping)

**Review by antonbabenko — APPROVED** [review]
LGTM because this addition is helpful for people who are now even using EKS but they still want to have the possibility to tag subnets differently.

**Comment by antonbabenko** [comment]
This PR is included in version 3.19.0 :tada:

**Pull request merged**
